
spring:
  # JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  #Databas Setting
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testgit
    username: sa
    password:
server:
  port: 8081
